<a href="https://colab.research.google.com/github/vrajkmrpatel/AI_ML_DATASCIENCE/blob/main/DataAnalysis/top_rated_movies.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import pandas as pd
import requests

In [68]:
API_KEY='8c39a78764a93839c04653314f6576ff'

In [19]:
url=f"https://api.themoviedb.org/3/movie/top_rated?api_key={API_KEY}&language=en-US&page=1"

In [28]:
genre_url=f"https://api.themoviedb.org/3/genre/movie/list?api_key={API_KEY}&language=en-US"

In [29]:
# Fetch all genre and save it in genre_df
genre_response = requests.get(genre_url)
genre_df = pd.DataFrame(genre_response.json()['genres'])
genre_df

       id             name
0      28           Action
1      12        Adventure
2      16        Animation
3      35           Comedy
4      80            Crime
5      99      Documentary
6      18            Drama
7   10751           Family
8      14          Fantasy
9      36          History
10     27           Horror
11  10402            Music
12   9648          Mystery
13  10749          Romance
14    878  Science Fiction
15  10770         TV Movie
16     53         Thriller
17  10752              War
18     37          Western

In [30]:
response = requests.get(url)

In [31]:
demo_df = pd.DataFrame(response.json()['results'])[['id','title','overview','genre_ids']]

In [32]:
demo_df.head()

,id,title,overview,genre_ids
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,"[18, 80]"
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","[18, 80]"
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,"[18, 80]"
3,424,Schindler's List,The true story of how businessman Oskar Schind...,"[18, 36, 10752]"
4,389,12 Angry Men,The defense and the prosecution have rested an...,[18]

In [ ]:
# iterate demo_df and change genre_ids by its field from genre_df
for i in range(len(demo_df)):
  demo_df['genre_ids'][i] = [genre_df[genre_df['id'] == x]['name'].values[0] for x in demo_df['genre_ids'][i]]

In [36]:
demo_df.head()

,id,title,overview,genre_ids
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,"[Drama, Crime]"
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","[Drama, Crime]"
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,"[Drama, Crime]"
3,424,Schindler's List,The true story of how businessman Oskar Schind...,"[Drama, History, War]"
4,389,12 Angry Men,The defense and the prosecution have rested an...,[Drama]

In [55]:
demo_df.shape

(20, 4)

In [56]:
df = pd.DataFrame()

In [57]:
df

Empty DataFrame
Columns: []
Index: []

In [58]:
for i in range(1, 534):
      url=f"https://api.themoviedb.org/3/movie/top_rated?api_key={API_KEY}&language=en-US&page={i}"
      response = requests.get(url)
      response_json = response.json()
      if 'results' in response_json and response_json['results']:
          temp_df = pd.DataFrame(response_json['results'])[['id','title','overview','genre_ids']]
          df = pd.concat([df, temp_df], ignore_index=True)
      else:
          print(f"No results or unexpected response for page {i}. Stopping data collection.")
          # print(response_json) # Uncomment for debugging to see the problematic response
          break

No results or unexpected response for page 501. Stopping data collection.

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         10000 non-null  int64
 1   title      10000 non-null  object
 2   overview   10000 non-null  object
 3   genre_ids  10000 non-null  object
dtypes: int64(1), object(3)
memory usage: 312.6+ KB

In [69]:
df.shape

(10000, 4)

In [70]:
df

,id,title,overview,genre_ids
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,"[Drama, Crime]"
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","[Drama, Crime]"
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,"[Drama, Crime]"
3,424,Schindler's List,The true story of how businessman Oskar Schind...,"[Drama, History, War]"
4,389,12 Angry Men,The defense and the prosecution have rested an...,[Drama]
...,...,...,...,...
9995,553141,The Head Hunter,"On the outskirts of a kingdom, a quiet but fie...","[Horror, Fantasy]"
9996,9612,Coneheads,A pair of aliens arrive on Earth to prepare fo...,"[Comedy, Science Fiction]"
9997,9356,Look Who's Talking Too,Mollie and James are together and raising a fa...,"[Romance, Comedy]"
9998,13493,College Road Trip,When an overachieving high school student deci...,"[Comedy, Family, Action, Adventure]"
9999,9592,Open Water 2: Adrift,A weekend cruise on a luxurious party yacht go...,"[Drama, Horror, Thriller]"

In [ ]:
# iterate df and change genre_ids by its field from genre_df
for i in range(len(df)):
  df['genre_ids'][i] = [genre_df[genre_df['id'] == x]['name'].values[0] for x in df['genre_ids'][i]]

In [67]:
df.sample(5)

,id,title,overview,genre_ids
7926,7303,Maid in Manhattan,Marisa Ventura is a struggling single mom who ...,"[Comedy, Drama, Romance]"
8145,507441,Sea Fever,The crew of a West of Ireland trawler—marooned...,"[Thriller, Horror, Drama, Science Fiction, Mys..."
8323,308531,Teenage Mutant Ninja Turtles: Out of the Shadows,"After supervillain Shredder escapes custody, h...","[Action, Adventure, Comedy, Family, Science Fi..."
8364,293767,Billy Lynn's Long Halftime Walk,19-year-old Billy Lynn is brought home for a v...,"[Drama, War]"
6207,622,The Ninth Gate,A rare book dealer finds himself at the heart ...,"[Mystery, Thriller, Horror]"

In [63]:
# df.to_csv("top_rated_movies.csv", index=False)