### One Hot Encoding

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('all_datasets/cars.csv')

In [41]:
df.sample(15)

         brand  km_driven    fuel                 owner  selling_price
5147    Maruti      70000  Diesel           First Owner         800000
6611  Mahindra     152000  Diesel  Fourth & Above Owner         200000
5816   Hyundai      30000  Petrol          Second Owner         370000
6562     Honda      56494  Petrol           First Owner         550000
6225    Maruti      39000  Petrol           First Owner          55000
7443   Hyundai      15000  Diesel           First Owner         800000
3829    Maruti     188000  Petrol  Fourth & Above Owner          70000
6291    Maruti      76000  Diesel           First Owner         725000
3911      Fiat      33003  Petrol           First Owner         265000
978    Hyundai      80000  Diesel           First Owner         650000
1303    Maruti     100000  Diesel           First Owner         511000
2056  Mahindra      60000  Diesel           First Owner         750000
3403  Mahindra     110000  Diesel          Second Owner         365000
1038    Toyota      60000  Diesel           First Owner         800000
1659  Mahindra     176000  Diesel          Second Owner         200000

In [45]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Kia                 4
Ambassador          4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [47]:
df.shape

(8128, 5)

### 1. One Hot Encoding using Pandas

In [48]:
pd.get_dummies(df, columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

### 2. K-1 OneHotEncoding

In [50]:
pd.get_dummies(df, columns=['fuel','owner'], drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

### 3. OneHotEncoding using Sklearn

In [51]:
from sklearn.model_selection import train_test_split

X_train,X_test, y_train, y_test = train_test_split(df.iloc[:,0:4], df.iloc[:,-1], test_size=0.2, random_state=0)

In [55]:
X_train.head()

         brand  km_driven    fuel         owner
3042   Hyundai      60000     LPG   First Owner
1520      Tata     150000  Diesel   Third Owner
2611   Hyundai     110000  Diesel  Second Owner
3544  Mahindra      28000  Diesel  Second Owner
4138    Maruti      15000  Petrol   First Owner

In [58]:
X_train.shape

(6502, 4)

In [56]:
from sklearn.preprocessing import OneHotEncoder

In [85]:
ohe = OneHotEncoder(drop='first') # drops the first category of each categorical feature

In [86]:
X_train_new = ohe.fit_transform(X_train[['fuel','owner']]).toarray()

In [87]:
X_test_new = ohe.transform(X_test[['fuel','owner']]).toarray()

In [88]:
X_train_new

array([[0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 1., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]], shape=(6502, 7))

In [89]:
X_train[['brand','km_driven']].values

array([['Hyundai', 60000],
       ['Tata', 150000],
       ['Hyundai', 110000],
       ...,
       ['Hyundai', 90000],
       ['Volkswagen', 90000],
       ['Hyundai', 110000]], shape=(6502, 2), dtype=object)

In [90]:
np.hstack((X_train[['brand','km_driven']].values, X_train_new)).shape

(6502, 9)

### 4. OneHotEncoding with Top Categories

In [93]:
counts = df['brand'].value_counts()

In [97]:
df['brand'].nunique()
threshold = 100

In [101]:
repl = counts[counts <= threshold].index

In [106]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon')).sample(10)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
6684,False,False,False,False,True,False,False,False,False,False,False,False,False
3258,False,False,False,False,False,False,True,False,False,False,False,False,False
3987,False,False,False,False,False,False,False,False,False,False,True,False,False
6646,False,False,False,False,False,False,True,False,False,False,False,False,False
2338,False,False,False,False,True,False,False,False,False,False,False,False,False
6265,False,False,False,False,False,False,False,False,False,False,False,False,True
3715,False,False,False,False,False,False,True,False,False,False,False,False,False
7192,False,False,False,False,False,False,True,False,False,False,False,False,False
4287,False,False,False,False,False,False,False,False,False,False,True,False,False
4371,False,False,False,False,True,False,False,False,False,False,False,False,False